language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
before_install:
  - composer self-update
install:
  - composer install --prefer-source --quiet --no-interaction --ignore-platform-reqs
